name: weather_spritewidget_example_remake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/clouds-0.png
    - assets/clouds-1.png
    - assets/icon-rain.png
    - assets/icon-snow.png
    - assets/icon-sun.png
    - assets/ray.png
    - assets/sun.png
    - assets/rain-drop.png
    - assets/flake-0.png
    - assets/flake-1.png
    - assets/flake-2.png
    - assets/flake-3.png
    - assets/flake-4.png
    - assets/flake-5.png
    - assets/flake-6.png
    - assets/flake-7.png
    - assets/flake-8.png

